// vue/component/input.vue
<template>
  <div class="r-input">
    <span v-if="$slots.prepend">
      <slot name="prepend"></slot>
    </span>
    <input v-bind="$attrs" />
  </div>
</template>

<style scoped>
.r-input {
  display: inline-block;
}
</style>

<script lang="ts">
import Vue from "vue";
export default Vue.extend({
  name: "RInput",
  props: {}
});
</script>

// src/client/component/input.svelte
<script lang="ts">
    import { onMount } from "svelte";
    export let id = "";
    export let type: string = "text";
    export let placeholder = "";
    export let value: string | number | undefined = undefined;
    export let readonly: boolean | undefined = undefined;

    let element: HTMLInputElement;
    onMount(() => {
        element.type = type;
    });
</script>

<div class="r-input">
    <slot name="prepend" />
    <input {id} {placeholder} {readonly} bind:value bind:this={element} />
</div>

<style>
    .r-input {
        display: inline-block;
        margin: 10px 0;
    }
</style>
